### ISSUE TITLE
log_capture cannot be imported on its own

### ISSUE THREAD

**Issue by jaklinger** [NHSDigital/nhs-context-logging#40]
The current README states that we can import the fixture `log_capture`
However this leads to an error where `log_capture_global` isn't found

Acceptance Criteria
* Either up date the README to suggest importing `log_capture_global`
* or eliminate the error

**Comment by matt-mercer** [comment]
docs have been updated to   suggest using 'import *

```python
# noinspection PyUnresolvedReferences
from nhs_context_logging.fixtures import *   # noqa: F403
```
